'use strict'

process.env.NODE_ENV = process.env.NODE_ENV or 'development'

express = require('express')
path = require('path')
favicon = require('serve-favicon')
morgan = require('morgan')
compression = require('compression')
bodyParser = require('body-parser')
passport = require('passport')
errorHandler = require('errorhandler')
mongoose = require('mongoose')
config = require('./config/environment')

# mongoose.connect config.mongo.uri, config.mongo.options

config =
  root: path.normalize(__dirname + '/..')
  env: process.env.NODE_ENV
  port: process.env.PORT or 7000
  ip: process.env.IP or undefined

app = express()
app.use compression()

# app.use bodyParser.json({limit: '5mb'})
# app.use bodyParser.urlencoded({limit: '5mb', extended: false})

app.use passport.initialize()
app.use passport.session()

require('./routes') app

if 'production' == config.env
  app.use morgan('dev')
  app.use favicon(path.join(config.root, 'public', 'favicon.ico'))
  app.use express['static'](path.join(config.root, 'public'))
  app.use (req, res, next) ->
    req.url = '/index.html'
    next()
  app.use express['static'](path.join(config.root, 'public'))

if 'development' == config.env or 'test' == config.env
  app.use require('connect-livereload')()
  app.use morgan('dev')
  app.use favicon(path.join(config.root, 'public', 'favicon.ico'))
  app.use express['static'](path.join(config.root, '.tmp'))
  app.use express['static'](path.join(config.root, 'public'))
  # console.log 'set'
  app.use (req, res, next) ->
    req.url = '/index.html'
    next()
  app.use express['static'](path.join(config.root, '.tmp'))
  app.use express['static'](path.join(config.root, 'public'))

  app.use errorHandler()

server = require('http').createServer(app)
server.listen config.port, config.ip, ->
  console.log 'Express server listening on %d, in %s mode', config.port, config.env
  return



exports = module.exports = app

# # ---
# # generated by js2coffee 2.0.4


# process.env.NODE_ENV = process.env.NODE_ENV or 'development'

# express = require('express')
# # mongoose = require('mongoose')
# config = require('./config/environment')

# # mongoose.connect config.mongo.uri, config.mongo.options

# app = express()

# server = require('http').createServer(app)

# require('./config/express') app
# require('./routes') app

# server.listen config.port, config.ip, ->
#   console.log 'Express server listening on %d, in %s mode', config.port, app.get('env')
#   return

# exports = module.exports = app
